services:
  postgres:
    image: postgres:15
    container_name: swe-lead-postgres
    environment:
      POSTGRES_DB: swe_lead_dev
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: